from datetime import UTC, datetime
from decimal import Decimal

from toss_trader.paper_timeline import build_paper_timeline
from toss_trader.timeline_web import create_timeline_server

payload = build_paper_timeline(
    initial_rows=(("rule", "1000000"), ("hermes", "1000000")),
    fill_rows=(
        (
            "rule",
            "rule:samsung-buy",
            "005930",
            "BUY",
            "2",
            "70000",
            "140000",
            "21",
            "0",
            "rule entry",
            datetime(2026, 8, 13, 1, tzinfo=UTC),
        ),
        (
            "hermes",
            "hermes:hynix-buy",
            "000660",
            "BUY",
            "1",
            "250000",
            "250000",
            "37.5",
            "0",
            "hermes entry",
            datetime(2026, 8, 13, 2, tzinfo=UTC),
        ),
    ),
    mark_rows=(
        ("005930", "삼성전자", "68000", "KRW", datetime(2026, 8, 12, 6, tzinfo=UTC)),
        ("000660", "SK하이닉스", "245000", "KRW", datetime(2026, 8, 12, 6, tzinfo=UTC)),
        ("005930", "삼성전자", "71000", "KRW", datetime(2026, 8, 13, 6, tzinfo=UTC)),
        ("000660", "SK하이닉스", "255000", "KRW", datetime(2026, 8, 13, 6, tzinfo=UTC)),
        ("005930", "삼성전자", "72000", "KRW", datetime(2026, 8, 14, 6, tzinfo=UTC)),
        ("000660", "SK하이닉스", "260000", "KRW", datetime(2026, 8, 14, 6, tzinfo=UTC)),
    ),
    cycle_rows=(
        (
            "rule",
            "succeeded",
            "5m",
            datetime(2026, 8, 13, tzinfo=UTC),
            None,
            "rule-cycle-1",
            datetime(2026, 8, 13, 0, 0, 12, tzinfo=UTC),
            15,
            1,
            1,
            0,
            0,
            "0.0012",
            {
                "idleReason": "setup-v2-block",
                "newBuysAllowed": True,
                "funnel": {"scanned": 15, "setupV2Blocked": 14, "fills": 1},
                "reasons": {"setup-v2-block": 14},
                "symbols": [
                    {
                        "symbol": "005930",
                        "reason": "setup-v2-block",
                        "skipReason": "setup-v2:violation:flow-not-confirmed",
                    }
                ],
            },
        ),
        (
            "hermes",
            "failed",
            "5m",
            datetime(2026, 8, 13, tzinfo=UTC),
            "Hermes API timeout",
            "hermes-cycle-1",
            datetime(2026, 8, 13, 0, 0, 15, tzinfo=UTC),
            15,
            0,
            0,
            1,
            1,
            "0",
            None,
        ),
    ),
    risk_rows=(
        (
            "rule",
            "rule:samsung-buy",
            "005930",
            "BUY",
            "MA20/MA60 trend entry",
            True,
            [],
            datetime(2026, 8, 13, 1, tzinfo=UTC),
        ),
        (
            "hermes",
            "hermes:hynix-buy",
            "000660",
            "BUY",
            "MA20/MA60 trend entry",
            True,
            [],
            datetime(2026, 8, 13, 2, tzinfo=UTC),
        ),
        (
            "hermes",
            "hermes:hanmi-reject",
            "042700",
            "BUY",
            "MA20/MA60 trend entry",
            False,
            ["Hermes 거부"],
            datetime(2026, 8, 13, 3, tzinfo=UTC),
        ),
    ),
    advice_rows=(
        (
            "succeeded",
            None,
            {
                "signalId": "hermes:hynix-buy",
                "approved": True,
                "rationale": "위험 한도 안입니다.",
            },
            datetime(2026, 8, 13, 2, 0, 1, tzinfo=UTC),
        ),
        (
            "succeeded",
            None,
            {
                "signalId": "hermes:hanmi-reject",
                "approved": False,
                "rationale": "변동성 정보가 부족합니다.",
            },
            datetime(2026, 8, 13, 3, 0, 1, tzinfo=UTC),
        ),
    ),
    name_rows=(("042700", "한미반도체"),),
    minute_rows=(
        (
            "005930",
            "70000",
            "71200",
            "69800",
            "71000",
            "1000",
            "KRW",
            datetime(2026, 8, 13, 1, tzinfo=UTC),
        ),
        (
            "005930",
            "71000",
            "72200",
            "70800",
            "72000",
            "1100",
            "KRW",
            datetime(2026, 8, 13, 1, 1, tzinfo=UTC),
        ),
        (
            "000660",
            "250000",
            "256000",
            "249000",
            "255000",
            "2000",
            "KRW",
            datetime(2026, 8, 13, 2, tzinfo=UTC),
        ),
    ),
    trend_rows=(
        ("005930", datetime(2026, 8, 11, 6, tzinfo=UTC), "67000"),
        ("005930", datetime(2026, 8, 12, 6, tzinfo=UTC), "68000"),
        ("005930", datetime(2026, 8, 13, 6, tzinfo=UTC), "71000"),
        ("005930", datetime(2026, 8, 14, 6, tzinfo=UTC), "72000"),
    ),
    hermes_log_rows=(
        (
            "trade-1",
            "hermes_trade",
            "succeeded",
            "decision",
            datetime(2026, 8, 13, 2, tzinfo=UTC),
            datetime(2026, 8, 13, 2, 0, 1, tzinfo=UTC),
            30,
            10,
            40,
            None,
            {
                "symbol": "000660",
                "side": "BUY",
                "approved": True,
                "rationale": "위험 한도 안입니다.",
            },
        ),
    ),
    momentum_log_rows=(
        (
            "hunter-1",
            "momentum-shadow",
            "succeeded",
            "evaluated",
            datetime(2026, 8, 14, 1, 1, tzinfo=UTC),
            datetime(2026, 8, 14, 1, 1, tzinfo=UTC),
            0,
            0,
            0,
            None,
            {
                "sessionDate": "2026-08-14",
                "ruleVersion": "momentum-shadow-v2",
                "selected": [
                    {
                        "symbol": "005930",
                        "entryAt": datetime(2026, 8, 14, 1, tzinfo=UTC).isoformat(),
                        "entryPrice": "70000",
                        "stopPrice": "69000",
                        "targetPrice": "71500",
                    }
                ],
            },
        ),
        (
            "hunter-advice-1",
            "momentum-shadow-advice",
            "succeeded",
            "decision",
            datetime(2026, 8, 14, 1, 1, tzinfo=UTC),
            datetime(2026, 8, 14, 1, 1, 1, tzinfo=UTC),
            40,
            10,
            50,
            None,
            {
                "sessionDate": "2026-08-14",
                "ruleVersion": "momentum-shadow-v2",
                "decisions": [
                    {
                        "symbol": "005930",
                        "verdict": "approve",
                        "rationale": "재돌파 유지력이 확인됐습니다.",
                    }
                ],
            },
        ),
    ),
    momentum_minute_rows=(
        (
            "005930",
            "70000",
            "71600",
            "69800",
            "71400",
            "1000",
            "KRW",
            datetime(2026, 8, 14, 1, tzinfo=UTC),
        ),
    ),
    default_initial_cash=Decimal(1000000),
)

with create_timeline_server(host="127.0.0.1", port=18091, payload=payload) as server:
    server.serve_forever()
