apiVersion: 1

datasources:
  - name: Toss Prometheus
    uid: toss-prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
